project:
  type: website
  output-dir: docs

website:
  title: "flaviamarsi.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual

